version: '3.4'

services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: n-teo-app-r.postgres
    restart: unless-stopped
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
        - 5432:5432
    volumes:
        - postgres:/var/lib/postgresql/data

volumes:
    postgres:
        driver: local